extends: spectral:oas
rules:
  operation-operationId:
    description: Every operation must define operationId.
    severity: error
    given: $.paths[*][*]
    then:
      field: operationId
      function: truthy
  operation-tags:
    description: Every operation must define at least one tag.
    severity: error
    given: $.paths[*][*]
    then:
      field: tags
      function: truthy
